Console.BackgroundColor = ConsoleColor.Black;
Console.ForegroundColor = ConsoleColor.DarkRed;
Console.Write("CO");
Console.BackgroundColor = ConsoleColor.Black;
Console.ForegroundColor =ConsoleColor.DarkRed;
Console.Write("RIN");
Console.BackgroundColor = ConsoleColor.Black;
Console.ForegroundColor = ConsoleColor.DarkRed; 
Console.Write("THI");
Console.BackgroundColor = ConsoleColor.Black;
Console.ForegroundColor =ConsoleColor.DarkRed;
Console.Write("ANS ");
Console.ForegroundColor = ConsoleColor.White;
Console.WriteLine("<3");
Console.ResetColor();